# Generated by Django 3.0.8 on 2020-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_education_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', models.ManyToManyField(to='personal.skills')),
            ],
        ),
    ]
