# Generated by Django 3.0.8 on 2020-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_awardandcertifications_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True)),
                ('workmode', models.BooleanField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
