# Generated by Django 3.0.8 on 2020-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='worksamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(blank=True, max_length=256)),
                ('link', models.URLField(blank=True, max_length=250)),
            ],
        ),
    ]
