# Generated by Django 3.0.8 on 2020-08-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
